# Generated by Django 5.0.1 on 2024-01-12 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_year', models.PositiveSmallIntegerField(max_length=4)),
                ('genre', models.CharField(choices=[('FICT', 'Fiction'), ('NF', 'Non-Fiction'), ('BIO', 'Biography'), ('USH', 'US History'), ('WH', 'World History'), ('PS', 'Political Science'), ('EDU', 'Education'), ('AUP', 'Architecture and Urban Planning')], default='NF', max_length=50)),
                ('number_in_collection', models.PositiveSmallIntegerField(default=1)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_app.author')),
            ],
        ),
    ]
