# Generated by Django 5.0.1 on 2024-01-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_admin',
        ),
    ]
