# Generated by Django 5.0.1 on 2024-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_author_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
