# Generated by Django 5.0.1 on 2024-01-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_book_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
