# Generated by Django 5.0.1 on 2024-01-17 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='library_app.location'),
        ),
    ]
