# Generated by Django 5.0.1 on 2024-01-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_alter_book_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
