# Generated by Django 4.2.9 on 2024-01-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_book_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommended_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(blank=True, default=None, null=True, related_name='reading_lists', to='library_app.book')),
            ],
        ),
    ]
