# Generated by Django 4.2.9 on 2024-01-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_book_recommended_by_readinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='books',
        ),
    ]
