# Generated by Django 4.2.9 on 2024-01-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_book_description_book_staff_blurb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issue', models.CharField(choices=[('ITEM', 'Item'), ('RESEARCH', 'Research'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField()),
                ('last_contact', models.DateField()),
                ('activity_log', models.TextField()),
            ],
        ),
    ]
