# Generated by Django 4.2.9 on 2024-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0014_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='activity_log',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_contact',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resolved',
            field=models.BooleanField(null=True),
        ),
    ]
