# Generated by Django 4.2.9 on 2024-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0017_alter_contact_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
